version: '3.1'

services:

  wordpress:
    image: "wordpress:latest"
    ports:
     - "80:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    volumes:
      - "wp-data:/var/www/html"

  database:
    image: "mysql:5.7"
    ports:
     - "3306:3306"    
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  wp-data:
  mysql-data:
